name: Scrape OGP thumbnails

on:
  workflow_dispatch:           # 手動実行ボタンを出す
  push:
    branches: [ main ]
    paths:
      - writings.html
      - .github/workflows/ogp-scrape.yml
      - tools/scrape-ogp.mjs
  schedule:
    - cron: '17 3 * * 1'       # 毎週月曜 03:17 UTC

permissions:
  contents: write              # JSONを自動コミットするために必要

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm --yes install cheerio node-fetch@3

      - name: Scrape OGP
        run: node tools/scrape-ogp.mjs

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(ogp): update writings-og.json'
          file_pattern: data/writings-og.json
