name: Scrape & Cache OGP thumbnails

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - writings.html
      - .github/workflows/ogp-scrape.yml
      - .github/workflows/ogp-cache.yml
      - tools/scrape-ogp.mjs
      - tools/cache-ogp.mjs
  schedule:
    - cron: '17 3 * * 1'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm --yes install cheerio node-fetch@3

      - name: Scrape OGP
        run: node tools/scrape-ogp.mjs

      - name: Cache OGP images locally
        run: node tools/cache-ogp.mjs

      - name: Commit JSON and cached images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(ogp): update json and cache images'
          file_pattern: |
            data/writings-og.json
            assets/og/*
